name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download spaCy model
      run: python -m spacy download en_core_web_sm
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pip install pytest
        pytest test_dependency_parser.py -v
    
    - name: Test Streamlit app
      run: |
        pip install streamlit
        python -c "import streamlit; print('Streamlit import successful')"

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download spaCy model
      run: python -m spacy download en_core_web_sm
    
    - name: Create deployment package
      run: |
        mkdir deployment
        cp *.py deployment/
        cp requirements.txt deployment/
        cp README.md deployment/
        cp LICENSE deployment/
        tar -czf dependency-parsing-app.tar.gz deployment/
    
    - name: Upload deployment artifact
      uses: actions/upload-artifact@v3
      with:
        name: dependency-parsing-app
        path: dependency-parsing-app.tar.gz
